# Generated by Django 3.0.7 on 2020-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20200710_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
