# Generated by Django 3.0.7 on 2020-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
