# Generated by Django 3.0.7 on 2020-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_delete_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
            preserve_default=False,
        ),
    ]
