# Generated by Django 3.0.7 on 2020-07-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentdetail_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='std_class',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
