# Generated by Django 3.0.7 on 2020-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentdetail_std_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
