# Generated by Django 3.0.7 on 2020-07-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200716_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='std_class',
        ),
    ]
